name: Run py scripts
on:
    push
        

jobs:
  run_py_script:
    env:
        MY_NAME: ${{ secrets.MY_NAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: 'pypy3.9' 
      - name: run the python script
        run: python execute.py
        
